name: Supabase Keep-Alive

on:
  schedule:
    - cron: '0 0 */6 * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Network diagnostics
        run: |
          echo "Running network diagnostics..."
          echo "DNS lookup for Supabase domain:"
          nslookup qchqadqmxltihtmxjmxo.supabase.co || echo "DNS lookup failed"
          
          echo "Checking connectivity with ping:"
          ping -c 4 qchqadqmxltihtmxjmxo.supabase.co || echo "Ping failed"
          
          echo "Checking HTTPS connectivity with curl:"
          curl -v https://qchqadqmxltihtmxjmxo.supabase.co/rest/v1/ || echo "Curl failed"
      
      - name: Ping Supabase with curl
        run: |
          echo "Pinging Supabase with curl..."
          curl -v -X GET "$SUPABASE_URL/rest/v1/transitions?select=id&limit=1" \
            -H "apikey: $SUPABASE_KEY" \
            -H "Authorization: Bearer $SUPABASE_KEY"
          echo "Ping completed at $(date)"
        env:
          SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
