name: Supabase Keep-Alive

on:
  schedule:
    - cron: '0 0 */6 * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install @supabase/supabase-js
        
      - name: Run keep-alive script
        run: |
          node -e "
          const { createClient } = require('@supabase/supabase-js');

          async function keepAlive() {
            const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
            const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
            
            if (!supabaseUrl || !supabaseServiceKey) {
              console.error('Missing Supabase credentials');
              process.exit(1);
            }
            
            console.log('Running Supabase keep-alive...');
            
            const supabase = createClient(supabaseUrl, supabaseServiceKey);
            
            try {
              const { data, error } = await supabase
                .from('transitions')
                .select('id')
                .limit(1);
                
              if (error) throw error;
              
              console.log('Supabase keep-alive successful:', new Date().toISOString());
              console.log('Retrieved data:', data);
              process.exit(0);
            } catch (error) {
              console.error('Supabase keep-alive failed:', error);
              process.exit(1);
            }
          }

          keepAlive();
          "
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}